config/routes.rb
Grepruby::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions

  resources :posts
  match "blog" => "posts#index"

  match 'google30aecb4f32189612' => 'welcome#google30aecb4f32189612'
  root :to => 'welcome#index'

  
  mount Refinery::Core::Engine, :at => '/'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
  attr_accessible :content, :name, :title
  #validates_presence_of :name
  validates_presence_of :content
  validates_presence_of :title

  #validates :name, :format=>{:with=> /^([a-zA-z]+ ?)*$/, :message =>"only alphabatic characters allowed"}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
  authenticates_with_sorcery!
  # attr_accessible :title, :body
  attr_accessible :email, :password, :password_confirmation, :username, :remember_me_token
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :username
  validates_uniqueness_of :username

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def not_authenticated
    redirect_to login_url, :alert => "First login to access this page."
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :require_login, :except=>[:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Discussion was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to posts_path, :notice => "Logged in!"
    else
      flash.now[:alert] = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_filter :require_login, :only => :secret
  def index
  	@posts = Refinery::Blog::Post.all(:limit => 2)
  	#render :layout => false
  end


  def google30aecb4f32189612
  	render :layout => false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
		<!-- Footer -->	
	<footer>
	 <div class="footer-content ">
	 	<div class="container">
	 		    <div class="row">
				    <div class="span12">
					    <div class="row">
						    <div class="span8">
						    	<div class="row">
						    		<div class="menu-div">
							    		<div class="span2m">
							    			<ul class="footer-menu unstyled">
							    				<li class="header-list">Who we are</li>
							    				<li><a href="/about">About GrepRuby</a></li>
							    				<li><a href="/our-team">Our Team</a></li>
							    				<li style="margin-top: 15px;"><a href="https://www.facebook.com/pages/GrepRuby/323789384382834" style="margin-right: 10px;" target="_blank"><img src="/assets/facebook.png" alt="Facebook" title="like us"/></a> <a href="https://twitter.com/grepruby" target="_blank"><img src="/assets/twitter.png" alt="Twitter" title="follow us"/></a></li>
							    			</ul>
							    		</div>
							    		<div class="span2m">
							    			<ul class="footer-menu unstyled">
							    				<li class="header-list">How we can Help</li>
							    				<!--<li><a href="/service">Ruby on Rails Services</a></li>-->
							    			</ul>
							    		</div>
							    		<div class="span2m">
							    			<ul class="footer-menu unstyled">
							    				<li class="header-list">Who are with us</li>
							    				<li><a href="/our-project">Our Projects</a></li>
							    				<li><a href="/contact">[ JOIN TO THE GROUP ]</a></li>
							    			</ul>
							    		</div>
							    	</div>
						    	</div>
						    </div>
						    <div class="span4">
						    	<div class="contact-section OpenSansLight">
						    		<p class="email">GrepRuby Pvt. Ltd.</p>
						    		<p>312, Akashdeep Complex Sneh Nagar Sapna Sangeeta Road </p>
						    		<!--<p>21, Sneh Nagar Sapna Snageeta Road</p>-->
						    		<p>Indore, Madhaya Pradesh 452001</p>
						    		<p>Phone:0731-4279592,+917415380716</p>
						    		<p class="copyright">&copy; GrepRuby Pvt. Ltd.</p>
						    	</div>
						    </div>
					    </div>
				    </div>
				</div>
	 	</div>
	 </div>
	</footer>

app/views/layouts/_header.html.erb
<!-- Header -->
<header>
  <div class="header-content">
    <div class="container">
     <div id="bgheader"><!-- BEGIN: header -->
       <div id="header">
	      <a class="logo" href="/">GrepRuby</a>
	      <div class="nav">
		    <ul>
		      <li <% if params[:path].blank? and params[:controller] != "posts" %>class="selected" <% end %> ><a class="home" href="/">Home</a></li>
		      <li <% if params[:path]== "our-project" %> class="selected" <% end %> ><a class="work" href="/our-project">Work</a></li>
			  <li <% if params[:path]== "what-we-do" %> class="selected" <% end %> ><a class="services" href="/what-we-do">What we do</a></li>
			  <li <% if params[:path]== "our-team" %> class="selected" <% end %> ><a class="community" href="/our-team">Our team</a></li>
			  <li <% if params[:path]== "contact-us" %> class="selected" <% end %> ><a class="contact" href="/contact-us">Contact us</a></li>
	          <li <% if params[:controller] == "posts" %> class="selected" <% end %> ><a class="blog" href="/blog">Blog</a></li>
		    </ul>
		  </div>
        </div>
    </div><!-- END: header -->
	</div>
  </div>
</header>
<% if["posts","users","sessions"].include?( params[:controller]) %>
    <div class="navbar clearfix">
    <div class="navbar-inner">
    <div class="container">
    <!-- Be sure to leave the brand out there if you want it shown -->
<% if current_user %>
  <%= link_to "Logged in as", "javascript:void(0);" ,:class=>"brand"%>
  <%= link_to current_user.email, "javascript:void(0);" ,:class=>"brand"%>
  <%= link_to "Log out", logout_path ,:class=>"brand"%>
<% else %>
  <%= link_to "Sign up", signup_path ,:class=>"brand"%>
  <%= link_to "or", "javascript:void(0);" ,:class=>"brand"%> 
  <%= link_to "log in", login_path ,:class=>"brand"%>
<% end %>
    </div>
    </div>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <%= render :partial => "/refinery/head" %>
        <!--<title>GrepRuby: Ruby on Rails Internet Software Development</title>-->       

    </head>

    <body>
        <div style="display: none;" id="cboxOverlay"></div>
        <div class="" id="colorbox" style="padding-bottom: 50px; padding-right: 50px; display: none;">
            <div style="" id="cboxWrapper">
                <div style="">
                    <div style="float: left;" id="cboxTopLeft"></div>
                    <div style="float: left;" id="cboxTopCenter"></div>
                    <div style="float: left;" id="cboxTopRight"></div>
                </div>
                <div style="clear: left;">
                    <div style="float: left;" id="cboxMiddleLeft"></div>
                    <div style="float: left;" id="cboxContent">
                        <div class="" style="width: 0pt; height: 0pt; overflow: hidden;" id="cboxLoadedContent">
                        </div>
                        <div class="" style="" id="cboxLoadingOverlay"></div>
                        <div class="" style="" id="cboxLoadingGraphic"></div>
                        <div class="" style="" id="cboxTitle"></div>
                        <div class="" style="" id="cboxCurrent"></div>
                        <div class="" style="" id="cboxNext"></div>
                        <div class="" style="" id="cboxPrevious"></div>
                        <div class="" style="" id="cboxSlideshow"></div>
                        <div class="" style="" id="cboxClose"></div>
                    </div>
                    <div style="float: left;" id="cboxMiddleRight"></div>
                </div>
                <div style="clear: left;">
                    <div style="float: left;" id="cboxBottomLeft"></div>
                    <div style="float: left;" id="cboxBottomCenter"></div>
                    <div style="float: left;" id="cboxBottomRight"></div>
                </div>
            </div>
            <div style="position: absolute; width: 9999px; visibility: hidden; display: none;"></div>
        </div>

        <%= render 'layouts/header' %>
  
        <div id="content"><!-- BEGIN: content -->
            <%= yield %>
        </div><!-- END: content -->

        <%= render 'layouts/footer' %>


    </body>
</html>

app/views/posts/_edit_form.html.erb
<%= form_for(@post) do |f| %>
  <table>
    <div class="field">
      <tr>
        <td><%= f.label :title %></td>
        <td></td>
      </tr>
      <tr>
        <td>&nbsp&nbsp&nbsp<%= f.text_field :title %></td>
        <td><% if @post.errors[:title].present? %><%= @post.errors[:title] %><% end %></td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <td><%= f.label :content %></td>
        <td></td>
      </tr>
      <tr>
        <td>&nbsp&nbsp&nbsp<%= f.text_area :content, :style =>"width: 600px; height: 60px" %></td>
        <td><% if @post.errors[:content].present? %><%= @post.errors[:content] %><% end %></td>
      </tr>
    </div>
  </table>
  <br>
  <div class="actions">
    <table>
      <tr>
        <td>&nbsp&nbsp&nbsp<%= f.submit %></td>
        <td>&nbsp&nbsp&nbsp</td>
        <td><!--input type="button" value="Cancle" action="/posts" data-method="get" --></td>
      </tr>
    </table>   
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <table>
    <div class="field">
      <tr>
        <td><%= f.label :title %></td>
        <td></td>
      </tr>
      <tr>
        <td>&nbsp&nbsp&nbsp<%= f.text_field :title, :style =>"width: 590px;" %></td>
        <td><% if @post.errors[:title].present? %><%= @post.errors[:title] %><% end %></td>
      </tr>
    </div>
    <div class="field">
      <tr>
        <td><%= f.label :content %></td>
        <td></td>
      </tr>
      <tr>
        <td>&nbsp&nbsp&nbsp<%= f.text_area :content, :style =>"width: 600px; height: 90px", :id => "post_contant" %></td>
        <td><% if @post.errors[:content].present? %><%= @post.errors[:content] %><% end %></td>
      </tr>
    </div>
  </table>
  <br>
  <div class="actions">
    <table>
      <tr>
        <td>&nbsp&nbsp&nbsp<%= f.submit %></td>
        <td>&nbsp&nbsp&nbsp</td>
        <td><!--input type="button" value="Cancle" action="/posts" data-method="get" --></td>
      </tr>
    </table>   
  </div>
<% end %>
<script type="text/javascript">
  $('#post_contant').wysihtml5();
</script>

app/views/posts/edit.html.erb
<div class="discus_blog" >
	<br> <br>
	<div class = "discuss_form" >
		<font size ="6px"><%= link_to "Discussion", posts_path %> >> Edit Discussion </font>
		<br> <br>
		<%= render 'form' %>
	</div>
	<br> <br>
</div>

app/views/posts/index.html.erb
<div align = "center"><%= flash[:notice] %> </div>
<div class="discus_blog" >
  <br><br>
  <div class = "discuss_form">
    <div id = "post">
      <div>
        <font size = "6px"><u>Discussion Topics</u></font>  
        <div id = "add_new">
          <font size ="4px">&nbsp&nbsp Add new Discussion :&nbsp <u><%= link_to 'New Post', new_post_path, method: :get %></u> &nbsp&nbsp</font>
        </div>
      </div>
      <br>
      <ul>
        <% if @posts && @posts.length > 0 %>
          <% @posts.each do |post| %>
            <li>&nbsp&nbsp&nbsp<font size = "4px" ><%= link_to post.title.html_safe.capitalize, post_path(post.id), method: :get %></font></li>
          <% end %>
        <% end %>
      </ul>    
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="discus_blog" >
	<br> <br>
	<div class = "discuss_form" >
		<font size ="6px"><%= link_to "Discussion", posts_path %> >> Add New Discussion</font>
		<br> <br>	
		<%= render 'form' %>
	</div>
	<br> <br>	
</div>

app/views/posts/show.html.erb
<div class="discus_blog" >
	<br> <br>
	<div class = "discuss_form">
		<div id = "post">
			<font size ="6px"><%= link_to "Discussion", posts_path %></font>
			<br><br>
			<font size ="5px"> <b><%= @post.title.capitalize %></b> </font>
			<hr>
			<div id = "discus_contant">
				<table>
					<tbody>
						<tr>
							<td valign ="top"><%= image_tag("icon3.gif") %></td>
							<td>&nbsp&nbsp</td>
							<td><%= @post.content.html_safe.capitalize %><br>
								<font size="4px"><%= link_to "Edit", edit_post_path %></font>
							</td>
						</tr>
					</tbody>
				</table>				
				<br><br>
				<font size="5px">Answers</font>
				<hr>
				<!--put discuss comments here-->
			</div>			
		</div>
	</div>	
</div>

app/views/refinery/_content_page.html.erb
<%= render_content_page(@page, {
      :hide_sections => local_assigns[:hide_sections],
      :can_use_fallback => !local_assigns[:show_empty_sections] && !local_assigns[:remove_automatic_sections]
    }) %>
<%= render :partial => '/refinery/draft_page_message' unless @page.nil? or @page.live? -%>

app/views/refinery/_head.html.erb
<head>
  <meta charset='<%= Rails.application.config.encoding %>' />
  <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" /><![endif]-->
  <title><%= browser_title(yield(:title)) %></title>
  <%= raw(%(<meta name="description" content="#{@meta.meta_description}" />)) if @meta.meta_description.present? -%>
  <%= raw(%(<meta name="keywords" content="#{@meta.meta_keywords}">)) if @meta.meta_keywords.present? -%>
  <%= raw(%(<link rel="canonical" content="#{@canonical}" />)) if @canonical.present? -%>
  <%= csrf_meta_tags if Refinery::Core.authenticity_token_on_frontend -%>
  <%= yield :meta %>
 
  <%= stylesheet_link_tag 'styles', 'fonts' %>

  <link href="/assets/plateforn45/application.css" media="screen" rel="stylesheet" type="text/css">
  <link href="/assets/plateforn45/nivo-slider.css" media="screen" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag 'bootstrap'%>
  <link rel="stylesheet" type="text/css" href="/assets/bootstrap-wysihtml5.css"></link>
  <link rel="stylesheet" type="text/css" href="/assets/bootstrap.min.css"></link>
  <script src="/assets/plateforn45/track.js" data-site-id="4e39a464f5a1f53236000003" id="gauges-tracker" async="" type="text/javascript"></script>
  <script src="/assets/plateforn45/ga.js" async="" type="text/javascript"></script>
  <script src="/assets/plateforn45/application.js" type="text/javascript"></script>


  <script src="/assets/plateforn45/form.js" type="text/javascript"></script>

  <%= javascript_include_tag "application" %>

  <script type="text/javascript">
      $(document).ready(function() {
          $('#slide-scroll').nivoSlider({
              effect: 'fade',
              directionNav:false,
              slices: 1,
              controlNav:true,
              animSpeed:500,
              pauseTime:5000,
              startSlide:0
          });
      });
  </script>
</head>

app/views/refinery/blog/categories/show.html.erb
<!-- Content -->
<div id="content">
	
	<div class="container">
		<div class="pageTop">
			<h1>BLOG</h1>
		</div>
		<div class="row">
			<div class="span8">
				<div class="postList">
					<div class="post">
						<div class="postDetails">
							<span>
								<% content_for :body_content_title, @category.title %>

								<% content_for :body_content_left do %>
									<% if @posts.any? %>
										<section id="blog_posts">
											<%= render :partial => "/refinery/blog/shared/post", :collection => @posts %>
											<%= will_paginate @posts %>
										</section>
									<% else %>
										<p>
											<%= t('.no_posts') %>
										</p>
									<% end %>
								<% end %>

								
								<%= render :partial => "/refinery/content_page" %>
							    <% content_for :stylesheets, stylesheet_link_tag('refinery/blog/frontend') %>
 
							</span>
						</div>
					</div>
				</div>
			</div>
			<div class="span4">
				<div class="sideBlock">
					<%= render :partial => "/refinery/blog/shared/categories" %>
				</div>
			</div>

		</div>
	</div>
			
</div>

app/views/refinery/blog/posts/_comment.html.erb
<article class='blog_comment_message' id='<%= "comment-#{comment.to_param}" %>'>
	<%= image_tag comment.avatar_url, :alt => comment.name, :class => 'avatar' %>
	<%= simple_format auto_link(comment.message.to_s) %>
	<p>
		<%= t('by', :scope => 'refinery.blog.posts.comments', :who => comment.name) %>,
		<%= t('time_ago', :scope => 'refinery.blog.posts.comments', :time => time_ago_in_words(comment.created_at)) %>
	</p>

	<footer class='blog_comment_author'>
	</footer>
</article>

app/views/refinery/blog/posts/_comments.html.erb
<aside id="comments">
  <h2><%= t('title', :scope => 'refinery.blog.posts.show.comments') %></h2>
  <% if (comments = @post.comments.approved).any? %>
    <%= render :partial => "comment", :collection => comments %>
  <% else %>
    <p>
      <%= t('none', :scope => 'refinery.blog.shared.comments') %>.
    </p>
  <% end %>

  <% flash.each do |key, value| %>
    <div id='flash' class="flash flash_<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <h2><%= t('add', :scope => 'refinery.blog.posts.show.comments') %></h2>
  <%= form_for [refinery, :blog, @comment] do |f| %>
    <%= render :partial => "/refinery/admin/error_messages",
               :locals => {
                 :object => f.object,
                 :include_object_name => true
               } %>
    <div class='field'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class='field'>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div class='field message_field_comment'>
      <%= f.label :message %>
      <%= f.text_area :message, :rows => 6 %>
    </div>
    <div class='field form-actions'>
      <%= f.submit t('submit', :scope => 'refinery.blog.posts.show') %>
    </div>
  <% end %>
</aside>

app/views/refinery/blog/posts/_nav.html.erb
<nav id="next_prev_article">
  <% if @post.next.present? -%>
    <%= link_to (truncate(@post.next.title) + " &#187;").html_safe, 
                refinery.blog_post_path(@post.next), 
                :class => 'next' %>
  <% end -%>

  <%= link_to t('blog_home', :scope => 'refinery.blog.posts.show'), 
              refinery.blog_root_path, 
              :class => 'home' %>

  <% if @post.prev.present? -%>
    <%= link_to ("&#171; " + truncate(@post.prev.title)).html_safe, 
                refinery.blog_post_path(@post.prev), 
                :class => 'prev' %>
  <% end -%>
</nav><!-- /next_prev_article -->

app/views/refinery/blog/posts/_post.html.erb
<article id="blog_post">
  <header>
    <h1><%= @post.title %></h1>
    <section class='details'>
      <time datetime="<%=l @post.published_at.to_date, :format => :default %>" class='posted_at'>
        <%= t('created_at', :scope => 'refinery.blog.shared.posts', :when => l(@post.published_at.to_date, :format => :short)) %>
      </time>
      <%= content_tag(:div, "#{t('by', :scope => 'refinery.blog.posts.show')} #{@post.author.username}", :class => "blog_author") if @post.author.present? %>
      <% if @post.source_url.present? %>
        <div class='blog_source'>
          <%= "#{t('source', :scope => 'refinery.blog.posts.show')}: " %>
          <%= link_to (@post.source_url_title.blank? ? @post.source_url : @post.source_url_title), @post.source_url %>
        </div>
      <% end %>
      <% if (categories = @post.categories).any? %>
        <aside class='filed_in'>
          <%= t('filed_in', :scope => 'refinery.blog.posts.show') %>
          <% categories.each_with_index do |category, index| %>
            <%= link_to category.title, refinery.blog_category_path(category) -%><%= ',' if index < ((categories.length) - 1) %>
          <% end %>
        </aside>
      <% end %>
    </section>
  </header>
  <%= @post.body.html_safe %>

  <% if Refinery::Blog::Post::ShareThis.enabled? %>
    <span class="st_sharethis" displayText="ShareThis"></span>
  <% end %>
</article>
<%= render :partial => '/refinery/draft_page_message' unless @post.nil? or @post.live? -%>
<%= render 'nav' if next_or_previous?(@post) %>

app/views/refinery/blog/posts/archive.html.erb
<% content_for :title, "#{t('.blog_archive_for', :date => @archive_date.strftime('%B %Y'))}" %>

<% content_for :body_content_left do %>
  <h1><%= t('.blog_archive_for', :date => @archive_date.strftime('%B %Y')) %></h1>
  <% if @posts.any? %>
    <section id="blog_posts">
      <%= render :partial => "/refinery/blog/shared/post", :collection => @posts %>
    </section>
  <% else %>
    <p><%= t('.no_blog_articles_posted', :date => @archive_date.strftime('%B %Y')) %></p>
  <% end %>
<% end %>

<%= render :partial => '/refinery/blog/shared/body_content_right' %>

<%= render :partial => "/refinery/content_page" %>
<% content_for :stylesheets, stylesheet_link_tag('refinery/blog/frontend') %>

app/views/refinery/blog/posts/index.html.erb
<!-- Content -->
<div id="content">
	
	<div class="container">
		<div class="pageTop">
			<h1>Blog</h1>
		</div>
		<div class="pageContent">
			<div class="row">
				<div class="span8">
					<div class="postList">
						<div class="post">
							<div class="postDetails">
								<span>
									<% if @posts.any? %>
										<section id="blog_posts">
											<%= render :partial => "/refinery/blog/shared/post", :collection => @posts %>
											<%= will_paginate @posts %>
										</section>
								    <% else %>
										<p><%= t('.no_blog_articles_yet') %></p>
									<% end %>
	 
								</span>
							</div>
						</div>
					</div>
				</div>
				<div class="span4">
					<div class="sideBlock">
						<%= render :partial => "/refinery/blog/shared/categories" %>
					</div>
				</div>
	
			</div>
		</div>
	</div>
			
</div>

app/views/refinery/blog/posts/show.html.erb
<!-- Content -->
	<div id="content">
	
		<div class="container">
			<div class="row">
				<div class="span8">
					<div class="postList">
						<div class="post">
							<div class="postDetails">
								<span>
									<%= render 'post' %> 
								</span>
							</div>
							<div class="postDetails">
								<% if Refinery::Blog::Post.comments_allowed? %>
									<%= render 'comments'%>
								<% end %>
							
								<%= render :partial => '/refinery/blog/shared/body_content_right' %>
								<%= render :partial => "/refinery/content_page", :locals => { :remove_automatic_sections => true }  %>
								<% content_for :stylesheets, stylesheet_link_tag('refinery/blog/frontend') %>
								<% content_for :javascripts do %>
									<%# enable AJAX'd post nav at your own risk until html5 history API implemented. %>
									<%#= javascript_include_tag('refinery/blog/frontend') %>
									<script src="http://w.sharethis.com/button/buttons.js"></script>
									<script>stLight.options({publisher:'<%= Blog::Post::ShareThis.key %>'});</script>
								<% end if Refinery::Blog::Post::ShareThis.enabled? %>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
				
	</div>

app/views/refinery/blog/posts/tagged.html.erb
<!-- Content -->
	<div id="content">
	
		<div class="container">
			<div class="pageTop">
				<h1><% content_for :title, "#{t('.posts_tagged')} '#{@tag_name.titleize}'"  %>
</h1>
							</div>
			<div class="row">
				<div class="span8">
					<div class="postList">
						<div class="post">
							<div class="postTitle">
								<h2><a href=""><% content_for :body_content_title, "#{t('.posts_tagged')} &#8220;#{@tag_name.titleize}&#8221;".html_safe -%>
</a></h2>
							</div>
							<div class="postDetails">
								<span>
									<% content_for :body_content_left do %>
										<% if @posts.any? %>
											<section id="blog_posts">
												<%= render :partial => "/refinery/blog/shared/post", :collection => @posts %>
												<%= will_paginate @posts %>
											</section>
										<% else %>
											<p><%= t('.no_blog_articles_yet') %></p>
										<% end %>
									<% end %>
 
								</span>
							</div>
							<div class="postContent">
								<%= render :partial => '/refinery/blog/shared/body_content_right' %>

								<%= render :partial => "/refinery/content_page" %>
								<% content_for :stylesheets, stylesheet_link_tag('refinery/blog/frontend') %>

							</div>
						</div>
						
					</div>
				</div>
			</div>
		</div>
				
	</div>

app/views/refinery/blog/shared/_categories.html.erb
<% if @categories.any? %>
  <h3 class="sideTitle"><%= t('.title') %></h3>
  <ul class="unstyled">
    <% @categories.each do |category| %>
      <li<%= " class='selected'" if @category.present? and @category.id == category.id %>>
        <%= link_to "#{category.title} (#{category.post_count})", refinery.blog_category_path(category) %>
      </li>
    <% end %>
  </ul>
<% end %>